"""Load Blueprint audio functions from the verified catalogue JSON.

The catalogue is generated by ``scripts/export_catalogues.py`` from the
curated ``blueprint_audio.py`` data.  It replaces the old 26K-node scraped
``bp_node_specs.json`` with 55 verified, annotated audio functions.
"""

from __future__ import annotations

import json
import os
from typing import Any

_CATALOGUE_PATH = os.path.join(
    os.path.dirname(__file__), "blueprint_audio_catalogue.json",
)


def load_scraped_nodes() -> dict[str, Any]:
    """Load Blueprint audio functions from the verified catalogue.

    Returns dict keyed by function name, matching the schema expected
    by ``seed.py`` / ``_seed_blueprint_scraped()``:
        name -> {target, category, description, inputs, outputs, ...}

    Returns empty dict if the catalogue file is missing.
    """
    if not os.path.isfile(_CATALOGUE_PATH):
        return {}
    with open(_CATALOGUE_PATH, encoding="utf-8") as f:
        catalogue = json.load(f)

    nodes: dict[str, Any] = {}
    for func in catalogue.get("functions", []):
        name = func.get("name", "")
        if not name:
            continue
        # Map catalogue fields to the scraped-node schema the DB expects
        nodes[name] = {
            "target": func.get("class_name", ""),
            "category": "audio",
            "description": func.get("description", ""),
            "inputs": [
                {"name": p["name"], "type": p["type"]}
                for p in func.get("params", [])
            ],
            "outputs": [{"name": "ReturnValue", "type": func["returns"]}]
            if func.get("returns")
            else [],
            "slug": name.lower().replace(".", "-"),
            "ue_version": "5.4+",
            "path": "",
        }
    return nodes
