"""Math utility nodes: interpolation, random, noise, color, datetime, timespan.
Source: UKismetMathLibrary -- official Epic C++ API.
"""
from __future__ import annotations
from ue_audio_mcp.knowledge.blueprint_nodes import _n

# --- MATH INTERPOLATION (15 nodes) ---
_n("Lerp", "UKismetMathLibrary", "math_interpolation", "Linear interpolation between A and B by Alpha", ["interpolation", "lerp", "smooth", "audio"])
_n("Ease", "UKismetMathLibrary", "math_interpolation", "Eased interpolation with configurable function", ["interpolation", "lerp", "smooth", "audio"])
_n("VLerp", "UKismetMathLibrary", "math_interpolation", "Vector linear interpolation", ["interpolation", "lerp", "smooth", "audio"])
_n("VEase", "UKismetMathLibrary", "math_interpolation", "Vector eased interpolation", ["interpolation", "lerp", "smooth", "audio"])
_n("VInterpTo", "UKismetMathLibrary", "math_interpolation", "Interpolates vector toward target at given speed", ["interpolation", "lerp", "smooth", "audio"])
_n("VInterpTo_Constant", "UKismetMathLibrary", "math_interpolation", "Constant-speed vector interpolation", ["interpolation", "lerp", "smooth", "audio"])
_n("VectorSpringInterp", "UKismetMathLibrary", "math_interpolation", "Spring-based vector interpolation", ["interpolation", "lerp", "smooth", "audio"])
_n("Vector2DInterpTo", "UKismetMathLibrary", "math_interpolation", "2D vector interpolation toward target", ["interpolation", "lerp", "smooth", "audio"])
_n("Vector2DInterpTo_Constant", "UKismetMathLibrary", "math_interpolation", "Constant-speed 2D vector interpolation", ["interpolation", "lerp", "smooth", "audio"])
_n("RInterpTo", "UKismetMathLibrary", "math_interpolation", "Rotator interpolation toward target", ["interpolation", "lerp", "smooth", "audio"])
_n("RInterpTo_Constant", "UKismetMathLibrary", "math_interpolation", "Constant-speed rotator interpolation", ["interpolation", "lerp", "smooth", "audio"])
_n("TInterpTo", "UKismetMathLibrary", "math_interpolation", "Transform interpolation toward target", ["interpolation", "lerp", "smooth", "audio"])
_n("CInterpTo", "UKismetMathLibrary", "math_interpolation", "LinearColor interpolation toward target", ["interpolation", "lerp", "smooth", "audio"])
_n("FInterpTo", "UKismetMathLibrary", "math_interpolation", "Float interpolation toward target at given speed", ["interpolation", "lerp", "smooth", "audio"])
_n("FInterpTo_Constant", "UKismetMathLibrary", "math_interpolation", "Constant-speed float interpolation", ["interpolation", "lerp", "smooth", "audio"])

# --- MATH RANDOM (14 nodes) ---
_n("MakeRandomStream", "UKismetMathLibrary", "math_random", "Creates RandomStream from seed", ["random", "seed", "variation"])
_n("BreakRandomStream", "UKismetMathLibrary", "math_random", "Extracts seed from RandomStream", ["random", "seed", "variation"])
_n("SeedRandomStream", "UKismetMathLibrary", "math_random", "Seeds an existing stream", ["random", "seed", "variation"])
_n("ResetRandomStream", "UKismetMathLibrary", "math_random", "Resets stream to initial seed", ["random", "seed", "variation"])
_n("RandomBoolFromStream", "UKismetMathLibrary", "math_random", "Random bool from stream", ["random", "seed", "variation"])
_n("RandomIntegerFromStream", "UKismetMathLibrary", "math_random", "Random int from stream", ["random", "seed", "variation"])
_n("RandomIntegerInRangeFromStream", "UKismetMathLibrary", "math_random", "Random int in range from stream", ["random", "seed", "variation"])
_n("RandomFloatFromStream", "UKismetMathLibrary", "math_random", "Random float from stream", ["random", "seed", "variation"])
_n("RandomFloatInRangeFromStream", "UKismetMathLibrary", "math_random", "Random float in range from stream", ["random", "seed", "variation"])
_n("RandomUnitVectorFromStream", "UKismetMathLibrary", "math_random", "Random unit vector from stream", ["random", "seed", "variation"])
_n("RandomRotatorFromStream", "UKismetMathLibrary", "math_random", "Random rotator from stream", ["random", "seed", "variation"])
_n("RandomPointInBoundingBox", "UKismetMathLibrary", "math_random", "Random point within AABB", ["random", "seed", "variation"])
_n("RandomUnitVector", "UKismetMathLibrary", "math_random", "Random unit direction vector", ["random", "seed", "variation"])
_n("RandomRotator", "UKismetMathLibrary", "math_random", "Random rotator (optionally roll)", ["random", "seed", "variation"])

# --- MATH NOISE (7 nodes) ---
_n("PerlinNoise1D", "UKismetMathLibrary", "math_noise", "1D Perlin noise from value", ["noise", "perlin", "procedural", "audio"])
_n("WeightedMovingAverage_Float", "UKismetMathLibrary", "math_noise", "Weighted moving average (float)", ["noise", "perlin", "procedural", "audio"])
_n("WeightedMovingAverage_FVector", "UKismetMathLibrary", "math_noise", "Weighted moving average (vector)", ["noise", "perlin", "procedural", "audio"])
_n("WeightedMovingAverage_FRotator", "UKismetMathLibrary", "math_noise", "Weighted moving average (rotator)", ["noise", "perlin", "procedural", "audio"])
_n("DynamicWeightedMovingAverage_Float", "UKismetMathLibrary", "math_noise", "Dynamic weighted moving average", ["noise", "perlin", "procedural", "audio"])
_n("DynamicWeightedMovingAverage_FVector", "UKismetMathLibrary", "math_noise", "Dynamic weighted moving average (vec)", ["noise", "perlin", "procedural", "audio"])
_n("DynamicWeightedMovingAverage_FRotator", "UKismetMathLibrary", "math_noise", "Dynamic weighted moving average (rot)", ["noise", "perlin", "procedural", "audio"])

# --- MATH COLOR (38 nodes) ---
_n("MakeColor", "UKismetMathLibrary", "math_color", "Creates LinearColor from RGBA", ["color", "rgb", "hsv"])
_n("BreakColor", "UKismetMathLibrary", "math_color", "Breaks LinearColor into R, G, B, A", ["color", "rgb", "hsv"])
_n("HSVToRGB", "UKismetMathLibrary", "math_color", "HSV to RGB conversion", ["color", "rgb", "hsv"])
_n("RGBToHSV", "UKismetMathLibrary", "math_color", "RGB to HSV conversion", ["color", "rgb", "hsv"])
_n("HSVToRGB_Vector", "UKismetMathLibrary", "math_color", "HSV to RGB (vector form)", ["color", "rgb", "hsv"])
_n("RGBToHSV_Vector", "UKismetMathLibrary", "math_color", "RGB to HSV (vector form)", ["color", "rgb", "hsv"])
_n("Conv_ColorToLinearColor", "UKismetMathLibrary", "math_color", "FColor to LinearColor", ["color", "rgb", "hsv"])
_n("Conv_LinearColorToColor", "UKismetMathLibrary", "math_color", "LinearColor to FColor", ["color", "rgb", "hsv"])
_n("Conv_FloatToLinearColor", "UKismetMathLibrary", "math_color", "Float to grayscale LinearColor", ["color", "rgb", "hsv"])
_n("Conv_VectorToLinearColor", "UKismetMathLibrary", "math_color", "Vector (RGB) to LinearColor", ["color", "rgb", "hsv"])
_n("Conv_LinearColorToVector", "UKismetMathLibrary", "math_color", "LinearColor to Vector (RGB)", ["color", "rgb", "hsv"])
_n("CInterpTo_Color", "UKismetMathLibrary", "math_color", "Color interpolation toward target", ["color", "rgb", "hsv"])
_n("LinearColor_Red", "UKismetMathLibrary", "math_color", "Returns red constant", ["color", "rgb", "hsv"])
_n("LinearColor_Green", "UKismetMathLibrary", "math_color", "Returns green constant", ["color", "rgb", "hsv"])
_n("LinearColor_Blue", "UKismetMathLibrary", "math_color", "Returns blue constant", ["color", "rgb", "hsv"])
_n("LinearColor_White", "UKismetMathLibrary", "math_color", "Returns white constant", ["color", "rgb", "hsv"])
_n("LinearColor_Black", "UKismetMathLibrary", "math_color", "Returns black constant", ["color", "rgb", "hsv"])
_n("LinearColor_Yellow", "UKismetMathLibrary", "math_color", "Returns yellow constant", ["color", "rgb", "hsv"])
_n("LinearColor_Transparent", "UKismetMathLibrary", "math_color", "Returns transparent constant", ["color", "rgb", "hsv"])
_n("LinearColor_Gray", "UKismetMathLibrary", "math_color", "Returns gray constant", ["color", "rgb", "hsv"])
_n("LinearColorLerp", "UKismetMathLibrary", "math_color", "Linear color interpolation", ["color", "rgb", "hsv"])
_n("LinearColorLerpUsingHSV", "UKismetMathLibrary", "math_color", "Interpolation through HSV space", ["color", "rgb", "hsv"])
_n("LinearColor_Desaturated", "UKismetMathLibrary", "math_color", "Returns desaturated color", ["color", "rgb", "hsv"])
_n("LinearColor_Distance", "UKismetMathLibrary", "math_color", "Euclidean distance between colors", ["color", "rgb", "hsv"])
_n("LinearColor_GetLuminance", "UKismetMathLibrary", "math_color", "Returns luminance value", ["color", "rgb", "hsv"])
_n("LinearColor_GetMax", "UKismetMathLibrary", "math_color", "Returns max component value", ["color", "rgb", "hsv"])
_n("LinearColor_GetMin", "UKismetMathLibrary", "math_color", "Returns min component value", ["color", "rgb", "hsv"])
_n("LinearColor_IsNearEqual", "UKismetMathLibrary", "math_color", "Near-equality check", ["color", "rgb", "hsv"])
_n("LinearColor_Quantize", "UKismetMathLibrary", "math_color", "Quantizes to FColor", ["color", "rgb", "hsv"])
_n("LinearColor_QuantizeRound", "UKismetMathLibrary", "math_color", "Quantizes with rounding", ["color", "rgb", "hsv"])
_n("LinearColor_Set", "UKismetMathLibrary", "math_color", "Sets RGBA components", ["color", "rgb", "hsv"])
_n("LinearColor_SetFromHSV", "UKismetMathLibrary", "math_color", "Sets from HSV values", ["color", "rgb", "hsv"])
_n("LinearColor_SetFromPow22", "UKismetMathLibrary", "math_color", "Sets from gamma 2.2 encoded", ["color", "rgb", "hsv"])
_n("LinearColor_SetFromSRGB", "UKismetMathLibrary", "math_color", "Sets from sRGB encoded", ["color", "rgb", "hsv"])
_n("LinearColor_SetRandomHue", "UKismetMathLibrary", "math_color", "Sets random hue, full saturation", ["color", "rgb", "hsv"])
_n("LinearColor_SetTemperature", "UKismetMathLibrary", "math_color", "Sets from color temperature (Kelvin)", ["color", "rgb", "hsv"])
_n("LinearColor_ToNewOpacity", "UKismetMathLibrary", "math_color", "Returns color with new alpha", ["color", "rgb", "hsv"])
_n("LinearColor_ToRGBE", "UKismetMathLibrary", "math_color", "Converts to RGBE color", ["color", "rgb", "hsv"])

# --- MATH DATETIME (20 nodes) ---
_n("MakeDateTime", "UKismetMathLibrary", "math_datetime", "Creates DateTime from year/month/day/etc.", ["datetime", "time", "date"])
_n("BreakDateTime", "UKismetMathLibrary", "math_datetime", "Breaks DateTime into components", ["datetime", "time", "date"])
_n("Now", "UKismetMathLibrary", "math_datetime", "Returns current local date and time", ["datetime", "time", "date"])
_n("UtcNow", "UKismetMathLibrary", "math_datetime", "Returns current UTC date and time", ["datetime", "time", "date"])
_n("Today", "UKismetMathLibrary", "math_datetime", "Returns today's date (midnight)", ["datetime", "time", "date"])
_n("DateTimeFromString", "UKismetMathLibrary", "math_datetime", "Parses date string", ["datetime", "time", "date"])
_n("DateTimeFromIsoString", "UKismetMathLibrary", "math_datetime", "Parses ISO-8601 date string", ["datetime", "time", "date"])
_n("DateTimeMaxValue", "UKismetMathLibrary", "math_datetime", "Maximum representable DateTime", ["datetime", "time", "date"])
_n("DateTimeMinValue", "UKismetMathLibrary", "math_datetime", "Minimum representable DateTime", ["datetime", "time", "date"])
_n("DaysInMonth", "UKismetMathLibrary", "math_datetime", "Days in given year/month", ["datetime", "time", "date"])
_n("DaysInYear", "UKismetMathLibrary", "math_datetime", "Days in given year", ["datetime", "time", "date"])
_n("IsLeapYear", "UKismetMathLibrary", "math_datetime", "Leap year check", ["datetime", "time", "date"])
_n("GetYear", "UKismetMathLibrary", "math_datetime", "Extract year from DateTime", ["datetime", "time", "date"])
_n("GetMonth", "UKismetMathLibrary", "math_datetime", "Extract month from DateTime", ["datetime", "time", "date"])
_n("GetDay", "UKismetMathLibrary", "math_datetime", "Extract day from DateTime", ["datetime", "time", "date"])
_n("GetHour", "UKismetMathLibrary", "math_datetime", "Extract hour from DateTime", ["datetime", "time", "date"])
_n("GetMinute", "UKismetMathLibrary", "math_datetime", "Extract minute from DateTime", ["datetime", "time", "date"])
_n("GetSecond", "UKismetMathLibrary", "math_datetime", "Extract second from DateTime", ["datetime", "time", "date"])
_n("GetMillisecond", "UKismetMathLibrary", "math_datetime", "Extract millisecond from DateTime", ["datetime", "time", "date"])
_n("GetDayOfYear", "UKismetMathLibrary", "math_datetime", "Day number within the year", ["datetime", "time", "date"])

# --- MATH TIMESPAN (20 nodes) ---
_n("MakeTimespan", "UKismetMathLibrary", "math_timespan", "Creates from days/hours/minutes/seconds", ["timespan", "duration", "time"])
_n("MakeTimespan2", "UKismetMathLibrary", "math_timespan", "Creates with milliseconds parameter", ["timespan", "duration", "time"])
_n("BreakTimespan", "UKismetMathLibrary", "math_timespan", "Breaks into components", ["timespan", "duration", "time"])
_n("BreakTimespan2", "UKismetMathLibrary", "math_timespan", "Breaks with milliseconds", ["timespan", "duration", "time"])
_n("Add_TimespanTimespan", "UKismetMathLibrary", "math_timespan", "Timespan addition", ["timespan", "duration", "time"])
_n("Subtract_TimespanTimespan", "UKismetMathLibrary", "math_timespan", "Timespan subtraction", ["timespan", "duration", "time"])
_n("Multiply_TimespanFloat", "UKismetMathLibrary", "math_timespan", "Scalar multiplication", ["timespan", "duration", "time"])
_n("Divide_TimespanFloat", "UKismetMathLibrary", "math_timespan", "Scalar division", ["timespan", "duration", "time"])
_n("Add_DateTimeTimespan", "UKismetMathLibrary", "math_timespan", "DateTime + Timespan", ["timespan", "duration", "time"])
_n("Subtract_DateTimeTimespan", "UKismetMathLibrary", "math_timespan", "DateTime - Timespan", ["timespan", "duration", "time"])
_n("FromDays", "UKismetMathLibrary", "math_timespan", "Creates Timespan from days", ["timespan", "duration", "time"])
_n("FromHours", "UKismetMathLibrary", "math_timespan", "Creates Timespan from hours", ["timespan", "duration", "time"])
_n("FromMinutes", "UKismetMathLibrary", "math_timespan", "Creates Timespan from minutes", ["timespan", "duration", "time"])
_n("FromSeconds", "UKismetMathLibrary", "math_timespan", "Creates Timespan from seconds", ["timespan", "duration", "time"])
_n("FromMilliseconds", "UKismetMathLibrary", "math_timespan", "Creates Timespan from milliseconds", ["timespan", "duration", "time"])
_n("GetTotalDays", "UKismetMathLibrary", "math_timespan", "Total days in timespan", ["timespan", "duration", "time"])
_n("GetTotalHours", "UKismetMathLibrary", "math_timespan", "Total hours", ["timespan", "duration", "time"])
_n("GetTotalMinutes", "UKismetMathLibrary", "math_timespan", "Total minutes", ["timespan", "duration", "time"])
_n("GetTotalSeconds", "UKismetMathLibrary", "math_timespan", "Total seconds", ["timespan", "duration", "time"])
_n("GetTotalMilliseconds", "UKismetMathLibrary", "math_timespan", "Total milliseconds", ["timespan", "duration", "time"])
