"""Math core nodes: bool, byte, int, int64, float, trig.
Source: UKismetMathLibrary -- official Epic C++ API.
"""
from __future__ import annotations
from ue_audio_mcp.knowledge.blueprint_nodes import _n

# --- MATH_BOOL (11 nodes) ---
_n("Not_PreBool", "UKismetMathLibrary", "math_bool", "Logical NOT of a boolean", ["boolean", "logic", "condition"])
_n("EqualEqual_BoolBool", "UKismetMathLibrary", "math_bool", "Returns true if A equals B", ["boolean", "logic", "condition"])
_n("NotEqual_BoolBool", "UKismetMathLibrary", "math_bool", "Returns true if A does not equal B", ["boolean", "logic", "condition"])
_n("BooleanAND", "UKismetMathLibrary", "math_bool", "Logical AND of two booleans", ["boolean", "logic", "condition"])
_n("BooleanNAND", "UKismetMathLibrary", "math_bool", "Logical NAND of two booleans", ["boolean", "logic", "condition"])
_n("BooleanOR", "UKismetMathLibrary", "math_bool", "Logical OR of two booleans", ["boolean", "logic", "condition"])
_n("BooleanXOR", "UKismetMathLibrary", "math_bool", "Logical XOR of two booleans", ["boolean", "logic", "condition"])
_n("BooleanNOR", "UKismetMathLibrary", "math_bool", "Logical NOR of two booleans", ["boolean", "logic", "condition"])
_n("RandomBool", "UKismetMathLibrary", "math_bool", "Returns a random boolean value", ["boolean", "logic", "condition"])
_n("RandomBoolWithWeight", "UKismetMathLibrary", "math_bool", "Returns random bool with weighted probability", ["boolean", "logic", "condition"])
_n("RandomBoolWithWeightFromStream", "UKismetMathLibrary", "math_bool", "Random bool with weight from RandomStream", ["boolean", "logic", "condition"])

# --- MATH_BYTE (15 nodes) ---
_n("Multiply_ByteByte", "UKismetMathLibrary", "math_byte", "Multiplication (A * B)", ["byte", "arithmetic"])
_n("Divide_ByteByte", "UKismetMathLibrary", "math_byte", "Division (A / B)", ["byte", "arithmetic"])
_n("Percent_ByteByte", "UKismetMathLibrary", "math_byte", "Modulo (A % B)", ["byte", "arithmetic"])
_n("Add_ByteByte", "UKismetMathLibrary", "math_byte", "Addition (A + B)", ["byte", "arithmetic"])
_n("Subtract_ByteByte", "UKismetMathLibrary", "math_byte", "Subtraction (A - B)", ["byte", "arithmetic"])
_n("BMin", "UKismetMathLibrary", "math_byte", "Returns minimum of two bytes", ["byte", "arithmetic"])
_n("BMax", "UKismetMathLibrary", "math_byte", "Returns maximum of two bytes", ["byte", "arithmetic"])
_n("Less_ByteByte", "UKismetMathLibrary", "math_byte", "A < B", ["byte", "arithmetic"])
_n("Greater_ByteByte", "UKismetMathLibrary", "math_byte", "A > B", ["byte", "arithmetic"])
_n("LessEqual_ByteByte", "UKismetMathLibrary", "math_byte", "A <= B", ["byte", "arithmetic"])
_n("GreaterEqual_ByteByte", "UKismetMathLibrary", "math_byte", "A >= B", ["byte", "arithmetic"])
_n("EqualEqual_ByteByte", "UKismetMathLibrary", "math_byte", "A == B", ["byte", "arithmetic"])
_n("NotEqual_ByteByte", "UKismetMathLibrary", "math_byte", "A != B", ["byte", "arithmetic"])
_n("MaxOfByteArray", "UKismetMathLibrary", "math_byte", "Returns max value in byte array", ["byte", "arithmetic"])
_n("MinOfByteArray", "UKismetMathLibrary", "math_byte", "Returns min value in byte array", ["byte", "arithmetic"])

# --- MATH_INT (26 nodes) ---
_n("Multiply_IntInt", "UKismetMathLibrary", "math_int", "Multiplication (A * B)", ["integer", "arithmetic", "math"])
_n("Divide_IntInt", "UKismetMathLibrary", "math_int", "Division (A / B)", ["integer", "arithmetic", "math"])
_n("Percent_IntInt", "UKismetMathLibrary", "math_int", "Modulo (A % B)", ["integer", "arithmetic", "math"])
_n("Add_IntInt", "UKismetMathLibrary", "math_int", "Addition (A + B)", ["integer", "arithmetic", "math"])
_n("Subtract_IntInt", "UKismetMathLibrary", "math_int", "Subtraction (A - B)", ["integer", "arithmetic", "math"])
_n("Less_IntInt", "UKismetMathLibrary", "math_int", "A < B", ["integer", "arithmetic", "math"])
_n("Greater_IntInt", "UKismetMathLibrary", "math_int", "A > B", ["integer", "arithmetic", "math"])
_n("LessEqual_IntInt", "UKismetMathLibrary", "math_int", "A <= B", ["integer", "arithmetic", "math"])
_n("GreaterEqual_IntInt", "UKismetMathLibrary", "math_int", "A >= B", ["integer", "arithmetic", "math"])
_n("EqualEqual_IntInt", "UKismetMathLibrary", "math_int", "A == B", ["integer", "arithmetic", "math"])
_n("NotEqual_IntInt", "UKismetMathLibrary", "math_int", "A != B", ["integer", "arithmetic", "math"])
_n("InRange_IntInt", "UKismetMathLibrary", "math_int", "Returns true if value is within range [Min, Max]", ["integer", "arithmetic", "math"])
_n("And_IntInt", "UKismetMathLibrary", "math_int", "Bitwise AND", ["integer", "arithmetic", "math"])
_n("Xor_IntInt", "UKismetMathLibrary", "math_int", "Bitwise XOR", ["integer", "arithmetic", "math"])
_n("Or_IntInt", "UKismetMathLibrary", "math_int", "Bitwise OR", ["integer", "arithmetic", "math"])
_n("Not_Int", "UKismetMathLibrary", "math_int", "Bitwise NOT", ["integer", "arithmetic", "math"])
_n("SignOfInteger", "UKismetMathLibrary", "math_int", "Returns sign of integer (-1, 0, or 1)", ["integer", "arithmetic", "math"])
_n("RandomInteger", "UKismetMathLibrary", "math_int", "Returns random int in [0, Max)", ["integer", "arithmetic", "math"])
_n("RandomIntegerInRange", "UKismetMathLibrary", "math_int", "Returns random int in [Min, Max]", ["integer", "arithmetic", "math"])
_n("Min", "UKismetMathLibrary", "math_int", "Returns smaller of two ints", ["integer", "arithmetic", "math"])
_n("Max", "UKismetMathLibrary", "math_int", "Returns larger of two ints", ["integer", "arithmetic", "math"])
_n("Clamp", "UKismetMathLibrary", "math_int", "Clamps int to [Min, Max] range", ["integer", "arithmetic", "math"])
_n("Wrap", "UKismetMathLibrary", "math_int", "Wraps int to range", ["integer", "arithmetic", "math"])
_n("Abs_Int", "UKismetMathLibrary", "math_int", "Returns absolute value", ["integer", "arithmetic", "math"])
_n("MaxOfIntArray", "UKismetMathLibrary", "math_int", "Returns max value in int array", ["integer", "arithmetic", "math"])
_n("MinOfIntArray", "UKismetMathLibrary", "math_int", "Returns min value in int array", ["integer", "arithmetic", "math"])

# --- MATH_INT64 (22 nodes) ---
_n("Multiply_Int64Int64", "UKismetMathLibrary", "math_int64", "Multiplication", ["integer", "int64", "arithmetic"])
_n("Divide_Int64Int64", "UKismetMathLibrary", "math_int64", "Division", ["integer", "int64", "arithmetic"])
_n("Add_Int64Int64", "UKismetMathLibrary", "math_int64", "Addition", ["integer", "int64", "arithmetic"])
_n("Subtract_Int64Int64", "UKismetMathLibrary", "math_int64", "Subtraction", ["integer", "int64", "arithmetic"])
_n("Less_Int64Int64", "UKismetMathLibrary", "math_int64", "A < B", ["integer", "int64", "arithmetic"])
_n("Greater_Int64Int64", "UKismetMathLibrary", "math_int64", "A > B", ["integer", "int64", "arithmetic"])
_n("LessEqual_Int64Int64", "UKismetMathLibrary", "math_int64", "A <= B", ["integer", "int64", "arithmetic"])
_n("GreaterEqual_Int64Int64", "UKismetMathLibrary", "math_int64", "A >= B", ["integer", "int64", "arithmetic"])
_n("EqualEqual_Int64Int64", "UKismetMathLibrary", "math_int64", "A == B", ["integer", "int64", "arithmetic"])
_n("NotEqual_Int64Int64", "UKismetMathLibrary", "math_int64", "A != B", ["integer", "int64", "arithmetic"])
_n("InRange_Int64Int64", "UKismetMathLibrary", "math_int64", "Value within range check", ["integer", "int64", "arithmetic"])
_n("And_Int64Int64", "UKismetMathLibrary", "math_int64", "Bitwise AND", ["integer", "int64", "arithmetic"])
_n("Xor_Int64Int64", "UKismetMathLibrary", "math_int64", "Bitwise XOR", ["integer", "int64", "arithmetic"])
_n("Or_Int64Int64", "UKismetMathLibrary", "math_int64", "Bitwise OR", ["integer", "int64", "arithmetic"])
_n("Not_Int64", "UKismetMathLibrary", "math_int64", "Bitwise NOT", ["integer", "int64", "arithmetic"])
_n("SignOfInteger64", "UKismetMathLibrary", "math_int64", "Returns sign (-1, 0, or 1)", ["integer", "int64", "arithmetic"])
_n("RandomInteger64", "UKismetMathLibrary", "math_int64", "Random int64", ["integer", "int64", "arithmetic"])
_n("RandomInteger64InRange", "UKismetMathLibrary", "math_int64", "Random int64 in range", ["integer", "int64", "arithmetic"])
_n("MinInt64", "UKismetMathLibrary", "math_int64", "Returns smaller of two int64s", ["integer", "int64", "arithmetic"])
_n("MaxInt64", "UKismetMathLibrary", "math_int64", "Returns larger of two int64s", ["integer", "int64", "arithmetic"])
_n("ClampInt64", "UKismetMathLibrary", "math_int64", "Clamps int64 to range", ["integer", "int64", "arithmetic"])
_n("Abs_Int64", "UKismetMathLibrary", "math_int64", "Absolute value", ["integer", "int64", "arithmetic"])

# --- MATH_FLOAT (51 nodes) ---
_n("MultiplyMultiply_FloatFloat", "UKismetMathLibrary", "math_float", "Power (A ^ B)", ["float", "arithmetic", "math"])
_n("Multiply_FloatFloat", "UKismetMathLibrary", "math_float", "Multiplication (A * B)", ["float", "arithmetic", "math"])
_n("Multiply_IntFloat", "UKismetMathLibrary", "math_float", "Int * Float", ["float", "arithmetic", "math"])
_n("Divide_FloatFloat", "UKismetMathLibrary", "math_float", "Division (A / B)", ["float", "arithmetic", "math"])
_n("Percent_FloatFloat", "UKismetMathLibrary", "math_float", "Modulo", ["float", "arithmetic", "math"])
_n("Fraction", "UKismetMathLibrary", "math_float", "Returns fractional part of float", ["float", "arithmetic", "math"])
_n("Add_FloatFloat", "UKismetMathLibrary", "math_float", "Addition", ["float", "arithmetic", "math"])
_n("Subtract_FloatFloat", "UKismetMathLibrary", "math_float", "Subtraction", ["float", "arithmetic", "math"])
_n("Less_FloatFloat", "UKismetMathLibrary", "math_float", "A < B", ["float", "arithmetic", "math"])
_n("Greater_FloatFloat", "UKismetMathLibrary", "math_float", "A > B", ["float", "arithmetic", "math"])
_n("LessEqual_FloatFloat", "UKismetMathLibrary", "math_float", "A <= B", ["float", "arithmetic", "math"])
_n("GreaterEqual_FloatFloat", "UKismetMathLibrary", "math_float", "A >= B", ["float", "arithmetic", "math"])
_n("EqualEqual_FloatFloat", "UKismetMathLibrary", "math_float", "A == B", ["float", "arithmetic", "math"])
_n("NearlyEqual_FloatFloat", "UKismetMathLibrary", "math_float", "Approximate equality within tolerance", ["float", "arithmetic", "math"])
_n("NotEqual_FloatFloat", "UKismetMathLibrary", "math_float", "A != B", ["float", "arithmetic", "math"])
_n("InRange_FloatFloat", "UKismetMathLibrary", "math_float", "Value within range check", ["float", "arithmetic", "math"])
_n("Hypotenuse", "UKismetMathLibrary", "math_float", "Returns hypotenuse from width and height", ["float", "arithmetic", "math"])
_n("GridSnap_Float", "UKismetMathLibrary", "math_float", "Snaps value to nearest grid increment", ["float", "arithmetic", "math"])
_n("Abs", "UKismetMathLibrary", "math_float", "Absolute value of float", ["float", "arithmetic", "math"])
_n("Exp", "UKismetMathLibrary", "math_float", "Exponential (e^A)", ["float", "arithmetic", "math"])
_n("Log", "UKismetMathLibrary", "math_float", "Logarithm base 10", ["float", "arithmetic", "math"])
_n("Loge", "UKismetMathLibrary", "math_float", "Natural logarithm (ln)", ["float", "arithmetic", "math"])
_n("Sqrt", "UKismetMathLibrary", "math_float", "Square root", ["float", "arithmetic", "math"])
_n("Square", "UKismetMathLibrary", "math_float", "Square (A * A)", ["float", "arithmetic", "math"])
_n("RandomFloat", "UKismetMathLibrary", "math_float", "Random float in [0, 1)", ["float", "arithmetic", "math"])
_n("RandomFloatInRange", "UKismetMathLibrary", "math_float", "Random float in [Min, Max]", ["float", "arithmetic", "math"])
_n("FMin", "UKismetMathLibrary", "math_float", "Returns smaller of two floats", ["float", "arithmetic", "math"])
_n("FMax", "UKismetMathLibrary", "math_float", "Returns larger of two floats", ["float", "arithmetic", "math"])
_n("FClamp", "UKismetMathLibrary", "math_float", "Clamps float to [Min, Max]", ["float", "arithmetic", "math"])
_n("FWrap", "UKismetMathLibrary", "math_float", "Wraps float to range", ["float", "arithmetic", "math"])
_n("SafeDivide", "UKismetMathLibrary", "math_float", "Division that returns 0 on divide-by-zero", ["float", "arithmetic", "math"])
_n("MaxOfFloatArray", "UKismetMathLibrary", "math_float", "Returns max value in float array", ["float", "arithmetic", "math"])
_n("MinOfFloatArray", "UKismetMathLibrary", "math_float", "Returns min value in float array", ["float", "arithmetic", "math"])
_n("ClampAngle", "UKismetMathLibrary", "math_float", "Clamps angle to range", ["float", "arithmetic", "math"])
_n("Round", "UKismetMathLibrary", "math_float", "Rounds to nearest int", ["float", "arithmetic", "math"])
_n("FFloor", "UKismetMathLibrary", "math_float", "Rounds down to nearest int", ["float", "arithmetic", "math"])
_n("FTrunc", "UKismetMathLibrary", "math_float", "Truncates toward zero", ["float", "arithmetic", "math"])
_n("FCeil", "UKismetMathLibrary", "math_float", "Rounds up to nearest int", ["float", "arithmetic", "math"])
_n("Round64", "UKismetMathLibrary", "math_float", "Rounds to nearest int64", ["float", "arithmetic", "math"])
_n("FFloor64", "UKismetMathLibrary", "math_float", "Rounds down to int64", ["float", "arithmetic", "math"])
_n("FTrunc64", "UKismetMathLibrary", "math_float", "Truncates to int64", ["float", "arithmetic", "math"])
_n("FCeil64", "UKismetMathLibrary", "math_float", "Rounds up to int64", ["float", "arithmetic", "math"])
_n("FMod", "UKismetMathLibrary", "math_float", "Floating-point modulo", ["float", "arithmetic", "math"])
_n("SignOfFloat", "UKismetMathLibrary", "math_float", "Returns sign (-1.0, 0.0, or 1.0)", ["float", "arithmetic", "math"])
_n("NormalizeToRange", "UKismetMathLibrary", "math_float", "Normalizes value to [0, 1] range given min/max", ["float", "arithmetic", "math"])
_n("MapRangeUnclamped", "UKismetMathLibrary", "math_float", "Maps value from one range to another (no clamping)", ["float", "arithmetic", "math"])
_n("MapRangeClamped", "UKismetMathLibrary", "math_float", "Maps value from one range to another (clamped)", ["float", "arithmetic", "math"])
_n("MultiplyByPi", "UKismetMathLibrary", "math_float", "Multiplies value by PI", ["float", "arithmetic", "math"])
_n("FInterpEaseInOut", "UKismetMathLibrary", "math_float", "Ease-in-out interpolation", ["float", "arithmetic", "math"])
_n("MakePulsatingValue", "UKismetMathLibrary", "math_float", "Creates pulsating value from time input", ["float", "arithmetic", "math"])
_n("FixedTurn", "UKismetMathLibrary", "math_float", "Returns angle clamped by max turn rate", ["float", "arithmetic", "math"])

# --- MATH_TRIG (18 nodes) ---
_n("Sin", "UKismetMathLibrary", "math_trig", "Sine (radians input)", ["trigonometry", "angle", "audio"])
_n("Asin", "UKismetMathLibrary", "math_trig", "Arc sine (returns radians)", ["trigonometry", "angle", "audio"])
_n("Cos", "UKismetMathLibrary", "math_trig", "Cosine (radians input)", ["trigonometry", "angle", "audio"])
_n("Acos", "UKismetMathLibrary", "math_trig", "Arc cosine (returns radians)", ["trigonometry", "angle", "audio"])
_n("Tan", "UKismetMathLibrary", "math_trig", "Tangent (radians input)", ["trigonometry", "angle", "audio"])
_n("Atan", "UKismetMathLibrary", "math_trig", "Arc tangent (returns radians)", ["trigonometry", "angle", "audio"])
_n("Atan2", "UKismetMathLibrary", "math_trig", "Arc tangent of Y/X (returns radians)", ["trigonometry", "angle", "audio"])
_n("GetPI", "UKismetMathLibrary", "math_trig", "Returns PI constant", ["trigonometry", "angle", "audio"])
_n("GetTAU", "UKismetMathLibrary", "math_trig", "Returns TAU constant (2*PI)", ["trigonometry", "angle", "audio"])
_n("DegreesToRadians", "UKismetMathLibrary", "math_trig", "Converts degrees to radians", ["trigonometry", "angle", "audio"])
_n("RadiansToDegrees", "UKismetMathLibrary", "math_trig", "Converts radians to degrees", ["trigonometry", "angle", "audio"])
_n("DegSin", "UKismetMathLibrary", "math_trig", "Sine (degrees input)", ["trigonometry", "angle", "audio"])
_n("DegAsin", "UKismetMathLibrary", "math_trig", "Arc sine (returns degrees)", ["trigonometry", "angle", "audio"])
_n("DegCos", "UKismetMathLibrary", "math_trig", "Cosine (degrees input)", ["trigonometry", "angle", "audio"])
_n("DegAcos", "UKismetMathLibrary", "math_trig", "Arc cosine (returns degrees)", ["trigonometry", "angle", "audio"])
_n("DegTan", "UKismetMathLibrary", "math_trig", "Tangent (degrees input)", ["trigonometry", "angle", "audio"])
_n("DegAtan", "UKismetMathLibrary", "math_trig", "Arc tangent (returns degrees)", ["trigonometry", "angle", "audio"])
_n("DegAtan2", "UKismetMathLibrary", "math_trig", "Arc tangent of Y/X (returns degrees)", ["trigonometry", "angle", "audio"])
