"""Math spatial nodes: intpoint, vector2d, vector, rotator, quat, transform.
Source: UKismetMathLibrary -- official Epic C++ API.
"""
from __future__ import annotations
from ue_audio_mcp.knowledge.blueprint_nodes import _n

# ===================================================================
# INTPOINT (17 nodes)
# ===================================================================
_n("IntPoint_Zero", "UKismetMathLibrary", "math_intpoint", "Returns (0,0) IntPoint constant", ["intpoint", "2d", "coordinate"])
_n("IntPoint_One", "UKismetMathLibrary", "math_intpoint", "Returns (1,1) IntPoint constant", ["intpoint", "2d", "coordinate"])
_n("IntPoint_Up", "UKismetMathLibrary", "math_intpoint", "Returns up direction IntPoint", ["intpoint", "2d", "coordinate"])
_n("IntPoint_Left", "UKismetMathLibrary", "math_intpoint", "Returns left direction IntPoint", ["intpoint", "2d", "coordinate"])
_n("IntPoint_Right", "UKismetMathLibrary", "math_intpoint", "Returns right direction IntPoint", ["intpoint", "2d", "coordinate"])
_n("IntPoint_Down", "UKismetMathLibrary", "math_intpoint", "Returns down direction IntPoint", ["intpoint", "2d", "coordinate"])
_n("Conv_IntPointToVector2D", "UKismetMathLibrary", "math_intpoint", "Converts IntPoint to Vector2D", ["intpoint", "2d", "coordinate"])
_n("Add_IntPointIntPoint", "UKismetMathLibrary", "math_intpoint", "IntPoint addition", ["intpoint", "2d", "coordinate"])
_n("Add_IntPointInt", "UKismetMathLibrary", "math_intpoint", "Add scalar to IntPoint", ["intpoint", "2d", "coordinate"])
_n("Subtract_IntPointIntPoint", "UKismetMathLibrary", "math_intpoint", "IntPoint subtraction", ["intpoint", "2d", "coordinate"])
_n("Subtract_IntPointInt", "UKismetMathLibrary", "math_intpoint", "Subtract scalar from IntPoint", ["intpoint", "2d", "coordinate"])
_n("Multiply_IntPointIntPoint", "UKismetMathLibrary", "math_intpoint", "IntPoint multiplication", ["intpoint", "2d", "coordinate"])
_n("Multiply_IntPointInt", "UKismetMathLibrary", "math_intpoint", "Multiply IntPoint by scalar", ["intpoint", "2d", "coordinate"])
_n("Divide_IntPointIntPoint", "UKismetMathLibrary", "math_intpoint", "IntPoint division", ["intpoint", "2d", "coordinate"])
_n("Divide_IntPointInt", "UKismetMathLibrary", "math_intpoint", "Divide IntPoint by scalar", ["intpoint", "2d", "coordinate"])
_n("Equal_IntPointIntPoint", "UKismetMathLibrary", "math_intpoint", "IntPoint equality check", ["intpoint", "2d", "coordinate"])
_n("NotEqual_IntPointIntPoint", "UKismetMathLibrary", "math_intpoint", "IntPoint inequality check", ["intpoint", "2d", "coordinate"])

# ===================================================================
# VECTOR2D (42 nodes)
# ===================================================================
_n("Vector2D_One", "UKismetMathLibrary", "math_vector2d", "Returns (1,1) constant", ["vector2d", "2d", "math"])
_n("Vector2D_Unit45Deg", "UKismetMathLibrary", "math_vector2d", "Returns unit vector at 45 degrees", ["vector2d", "2d", "math"])
_n("Vector2D_Zero", "UKismetMathLibrary", "math_vector2d", "Returns (0,0) constant", ["vector2d", "2d", "math"])
_n("MakeVector2D", "UKismetMathLibrary", "math_vector2d", "Creates Vector2D from X, Y components", ["vector2d", "2d", "math"])
_n("BreakVector2D", "UKismetMathLibrary", "math_vector2d", "Breaks Vector2D into X, Y components", ["vector2d", "2d", "math"])
_n("Conv_Vector2DToVector", "UKismetMathLibrary", "math_vector2d", "Converts 2D to 3D vector (Z=0)", ["vector2d", "2d", "math"])
_n("Conv_Vector2DToIntPoint", "UKismetMathLibrary", "math_vector2d", "Converts Vector2D to IntPoint", ["vector2d", "2d", "math"])
_n("Add_Vector2DVector2D", "UKismetMathLibrary", "math_vector2d", "Vector2D addition", ["vector2d", "2d", "math"])
_n("Add_Vector2DFloat", "UKismetMathLibrary", "math_vector2d", "Add scalar to Vector2D", ["vector2d", "2d", "math"])
_n("Subtract_Vector2DVector2D", "UKismetMathLibrary", "math_vector2d", "Vector2D subtraction", ["vector2d", "2d", "math"])
_n("Subtract_Vector2DFloat", "UKismetMathLibrary", "math_vector2d", "Subtract scalar from Vector2D", ["vector2d", "2d", "math"])
_n("Multiply_Vector2DVector2D", "UKismetMathLibrary", "math_vector2d", "Component-wise multiplication", ["vector2d", "2d", "math"])
_n("Multiply_Vector2DFloat", "UKismetMathLibrary", "math_vector2d", "Scalar multiplication", ["vector2d", "2d", "math"])
_n("Divide_Vector2DVector2D", "UKismetMathLibrary", "math_vector2d", "Component-wise division", ["vector2d", "2d", "math"])
_n("Divide_Vector2DFloat", "UKismetMathLibrary", "math_vector2d", "Scalar division", ["vector2d", "2d", "math"])
_n("EqualExactly_Vector2DVector2D", "UKismetMathLibrary", "math_vector2d", "Exact equality check", ["vector2d", "2d", "math"])
_n("EqualEqual_Vector2DVector2D", "UKismetMathLibrary", "math_vector2d", "Approximate equality check", ["vector2d", "2d", "math"])
_n("NotEqualExactly_Vector2DVector2D", "UKismetMathLibrary", "math_vector2d", "Exact inequality check", ["vector2d", "2d", "math"])
_n("NotEqual_Vector2DVector2D", "UKismetMathLibrary", "math_vector2d", "Approximate inequality check", ["vector2d", "2d", "math"])
_n("Negated2D", "UKismetMathLibrary", "math_vector2d", "Returns negated vector", ["vector2d", "2d", "math"])
_n("Set2D", "UKismetMathLibrary", "math_vector2d", "Sets vector components", ["vector2d", "2d", "math"])
_n("ClampAxes2D", "UKismetMathLibrary", "math_vector2d", "Clamps each axis to range", ["vector2d", "2d", "math"])
_n("CrossProduct2D", "UKismetMathLibrary", "math_vector2d", "2D cross product", ["vector2d", "2d", "math"])
_n("Distance2D", "UKismetMathLibrary", "math_vector2d", "Distance between two 2D points", ["vector2d", "2d", "math"])
_n("DistanceSquared2D", "UKismetMathLibrary", "math_vector2d", "Squared distance (faster, no sqrt)", ["vector2d", "2d", "math"])
_n("DotProduct2D", "UKismetMathLibrary", "math_vector2d", "2D dot product", ["vector2d", "2d", "math"])
_n("GetAbs2D", "UKismetMathLibrary", "math_vector2d", "Absolute value of each component", ["vector2d", "2d", "math"])
_n("GetAbsMax2D", "UKismetMathLibrary", "math_vector2d", "Max of absolute component values", ["vector2d", "2d", "math"])
_n("GetMax2D", "UKismetMathLibrary", "math_vector2d", "Max component value", ["vector2d", "2d", "math"])
_n("GetMin2D", "UKismetMathLibrary", "math_vector2d", "Min component value", ["vector2d", "2d", "math"])
_n("GetRotated2D", "UKismetMathLibrary", "math_vector2d", "Rotates vector by angle in degrees", ["vector2d", "2d", "math"])
_n("IsNearlyZero2D", "UKismetMathLibrary", "math_vector2d", "Near-zero check with tolerance", ["vector2d", "2d", "math"])
_n("IsZero2D", "UKismetMathLibrary", "math_vector2d", "Exact zero check", ["vector2d", "2d", "math"])
_n("NormalSafe2D", "UKismetMathLibrary", "math_vector2d", "Safe normalization (handles zero)", ["vector2d", "2d", "math"])
_n("Normal2D", "UKismetMathLibrary", "math_vector2d", "Returns normalized vector", ["vector2d", "2d", "math"])
_n("Normalize2D", "UKismetMathLibrary", "math_vector2d", "Normalizes vector in-place", ["vector2d", "2d", "math"])
_n("Spherical2DToUnitCartesian", "UKismetMathLibrary", "math_vector2d", "Spherical to cartesian conversion", ["vector2d", "2d", "math"])
_n("ToDirectionAndLength2D", "UKismetMathLibrary", "math_vector2d", "Splits into direction + magnitude", ["vector2d", "2d", "math"])
_n("ToRounded2D", "UKismetMathLibrary", "math_vector2d", "Rounds each component", ["vector2d", "2d", "math"])
_n("ToSign2D", "UKismetMathLibrary", "math_vector2d", "Returns sign of each component", ["vector2d", "2d", "math"])
_n("VSize2D", "UKismetMathLibrary", "math_vector2d", "Vector magnitude (length)", ["vector2d", "2d", "math"])
_n("VSize2DSquared", "UKismetMathLibrary", "math_vector2d", "Squared magnitude (faster)", ["vector2d", "2d", "math"])

# ===================================================================
# VECTOR 3D -- Constants (8 nodes)
# ===================================================================
_n("Vector_Zero", "UKismetMathLibrary", "math_vector", "Returns (0,0,0)", ["vector", "3d", "spatial", "position"])
_n("Vector_One", "UKismetMathLibrary", "math_vector", "Returns (1,1,1)", ["vector", "3d", "spatial", "position"])
_n("Vector_Forward", "UKismetMathLibrary", "math_vector", "Returns forward direction (1,0,0)", ["vector", "3d", "spatial", "position"])
_n("Vector_Backward", "UKismetMathLibrary", "math_vector", "Returns backward direction (-1,0,0)", ["vector", "3d", "spatial", "position"])
_n("Vector_Up", "UKismetMathLibrary", "math_vector", "Returns up direction (0,0,1)", ["vector", "3d", "spatial", "position"])
_n("Vector_Down", "UKismetMathLibrary", "math_vector", "Returns down direction (0,0,-1)", ["vector", "3d", "spatial", "position"])
_n("Vector_Right", "UKismetMathLibrary", "math_vector", "Returns right direction (0,1,0)", ["vector", "3d", "spatial", "position"])
_n("Vector_Left", "UKismetMathLibrary", "math_vector", "Returns left direction (0,-1,0)", ["vector", "3d", "spatial", "position"])

# ===================================================================
# VECTOR 3D -- Operations (89 nodes)
# ===================================================================
_n("MakeVector", "UKismetMathLibrary", "math_vector", "Creates vector from X, Y, Z components", ["vector", "3d", "spatial", "position"])
_n("CreateVectorFromYawPitch", "UKismetMathLibrary", "math_vector", "Creates direction vector from yaw/pitch angles", ["vector", "3d", "spatial", "position"])
_n("Vector_Assign", "UKismetMathLibrary", "math_vector", "Assigns one vector to another", ["vector", "3d", "spatial", "position"])
_n("Vector_Set", "UKismetMathLibrary", "math_vector", "Sets vector X, Y, Z values", ["vector", "3d", "spatial", "position"])
_n("BreakVector", "UKismetMathLibrary", "math_vector", "Breaks vector into X, Y, Z", ["vector", "3d", "spatial", "position"])
_n("Conv_VectorToLinearColor", "UKismetMathLibrary", "math_vector", "Vector to LinearColor conversion", ["vector", "3d", "spatial", "position"])
_n("Conv_VectorToTransform", "UKismetMathLibrary", "math_vector", "Vector to Transform (as location)", ["vector", "3d", "spatial", "position"])
_n("Conv_VectorToVector2D", "UKismetMathLibrary", "math_vector", "3D to 2D (drops Z)", ["vector", "3d", "spatial", "position"])
_n("Conv_VectorToRotator", "UKismetMathLibrary", "math_vector", "Direction vector to rotator", ["vector", "3d", "spatial", "position"])
_n("Conv_VectorToQuaternion", "UKismetMathLibrary", "math_vector", "Euler angles to quaternion", ["vector", "3d", "spatial", "position"])
_n("RotatorFromAxisAndAngle", "UKismetMathLibrary", "math_vector", "Creates rotator from axis and angle", ["vector", "3d", "spatial", "position"])
_n("Add_VectorVector", "UKismetMathLibrary", "math_vector", "Vector addition", ["vector", "3d", "spatial", "position"])
_n("Add_VectorFloat", "UKismetMathLibrary", "math_vector", "Add scalar to all components", ["vector", "3d", "spatial", "position"])
_n("Add_VectorInt", "UKismetMathLibrary", "math_vector", "Add int to all components", ["vector", "3d", "spatial", "position"])
_n("Subtract_VectorVector", "UKismetMathLibrary", "math_vector", "Vector subtraction", ["vector", "3d", "spatial", "position"])
_n("Subtract_VectorFloat", "UKismetMathLibrary", "math_vector", "Subtract scalar from components", ["vector", "3d", "spatial", "position"])
_n("Subtract_VectorInt", "UKismetMathLibrary", "math_vector", "Subtract int from components", ["vector", "3d", "spatial", "position"])
_n("Multiply_VectorVector", "UKismetMathLibrary", "math_vector", "Component-wise multiply", ["vector", "3d", "spatial", "position"])
_n("Multiply_VectorFloat", "UKismetMathLibrary", "math_vector", "Scalar multiply", ["vector", "3d", "spatial", "position"])
_n("Multiply_VectorInt", "UKismetMathLibrary", "math_vector", "Int multiply", ["vector", "3d", "spatial", "position"])
_n("Divide_VectorVector", "UKismetMathLibrary", "math_vector", "Component-wise divide", ["vector", "3d", "spatial", "position"])
_n("Divide_VectorFloat", "UKismetMathLibrary", "math_vector", "Scalar divide", ["vector", "3d", "spatial", "position"])
_n("Divide_VectorInt", "UKismetMathLibrary", "math_vector", "Int divide", ["vector", "3d", "spatial", "position"])
_n("NegateVector", "UKismetMathLibrary", "math_vector", "Returns negated vector", ["vector", "3d", "spatial", "position"])
_n("EqualExactly_VectorVector", "UKismetMathLibrary", "math_vector", "Exact equality", ["vector", "3d", "spatial", "position"])
_n("EqualEqual_VectorVector", "UKismetMathLibrary", "math_vector", "Approximate equality", ["vector", "3d", "spatial", "position"])
_n("NotEqualExactly_VectorVector", "UKismetMathLibrary", "math_vector", "Exact inequality", ["vector", "3d", "spatial", "position"])
_n("NotEqual_VectorVector", "UKismetMathLibrary", "math_vector", "Approximate inequality", ["vector", "3d", "spatial", "position"])
_n("Dot_VectorVector", "UKismetMathLibrary", "math_vector", "Dot product", ["vector", "3d", "spatial", "position"])
_n("Cross_VectorVector", "UKismetMathLibrary", "math_vector", "Cross product", ["vector", "3d", "spatial", "position"])
_n("GreaterGreater_VectorRotator", "UKismetMathLibrary", "math_vector", "Rotate vector by rotator (>>)", ["vector", "3d", "spatial", "position"])
_n("RotateAngleAxis", "UKismetMathLibrary", "math_vector", "Rotates vector around axis by angle", ["vector", "3d", "spatial", "position"])
_n("LessLess_VectorRotator", "UKismetMathLibrary", "math_vector", "Unrotate vector by rotator (<<)", ["vector", "3d", "spatial", "position"])
_n("Vector_UnwindEuler", "UKismetMathLibrary", "math_vector", "Unwinds Euler angles to [-180, 180]", ["vector", "3d", "spatial", "position"])
_n("ClampVectorSize", "UKismetMathLibrary", "math_vector", "Clamps vector magnitude to range", ["vector", "3d", "spatial", "position"])
_n("Vector_ClampSize2D", "UKismetMathLibrary", "math_vector", "Clamps 2D magnitude", ["vector", "3d", "spatial", "position"])
_n("Vector_ClampSizeMax", "UKismetMathLibrary", "math_vector", "Clamps to maximum magnitude", ["vector", "3d", "spatial", "position"])
_n("Vector_ClampSizeMax2D", "UKismetMathLibrary", "math_vector", "Clamps 2D to maximum magnitude", ["vector", "3d", "spatial", "position"])
_n("GetMinElement", "UKismetMathLibrary", "math_vector", "Returns smallest component", ["vector", "3d", "spatial", "position"])
_n("GetMaxElement", "UKismetMathLibrary", "math_vector", "Returns largest component", ["vector", "3d", "spatial", "position"])
_n("Vector_GetAbsMax", "UKismetMathLibrary", "math_vector", "Max of absolute components", ["vector", "3d", "spatial", "position"])
_n("Vector_GetAbsMin", "UKismetMathLibrary", "math_vector", "Min of absolute components", ["vector", "3d", "spatial", "position"])
_n("Vector_GetAbs", "UKismetMathLibrary", "math_vector", "Absolute value of each component", ["vector", "3d", "spatial", "position"])
_n("Vector_ComponentMin", "UKismetMathLibrary", "math_vector", "Per-component min of two vectors", ["vector", "3d", "spatial", "position"])
_n("Vector_ComponentMax", "UKismetMathLibrary", "math_vector", "Per-component max of two vectors", ["vector", "3d", "spatial", "position"])
_n("Vector_GetSignVector", "UKismetMathLibrary", "math_vector", "Sign of each component", ["vector", "3d", "spatial", "position"])
_n("Vector_GetProjection", "UKismetMathLibrary", "math_vector", "Projects vector onto plane", ["vector", "3d", "spatial", "position"])
_n("Vector_HeadingAngle", "UKismetMathLibrary", "math_vector", "Returns heading angle in radians", ["vector", "3d", "spatial", "position"])
_n("Vector_CosineAngle2D", "UKismetMathLibrary", "math_vector", "Cosine of 2D angle between vectors", ["vector", "3d", "spatial", "position"])
_n("Vector_ToRadians", "UKismetMathLibrary", "math_vector", "Converts degree components to radians", ["vector", "3d", "spatial", "position"])
_n("Vector_ToDegrees", "UKismetMathLibrary", "math_vector", "Converts radian components to degrees", ["vector", "3d", "spatial", "position"])
_n("Vector_UnitCartesianToSpherical", "UKismetMathLibrary", "math_vector", "Cartesian to spherical coordinates", ["vector", "3d", "spatial", "position"])
_n("GetDirectionUnitVector", "UKismetMathLibrary", "math_vector", "Unit direction from A to B", ["vector", "3d", "spatial", "position"])
_n("GetYawPitchFromVector", "UKismetMathLibrary", "math_vector", "Extracts yaw/pitch from direction", ["vector", "3d", "spatial", "position"])
_n("GetAzimuthAndElevation", "UKismetMathLibrary", "math_vector", "Direction to azimuth + elevation", ["vector", "3d", "spatial", "position"])
_n("GetVectorArrayAverage", "UKismetMathLibrary", "math_vector", "Average of vector array", ["vector", "3d", "spatial", "position"])
_n("FTruncVector", "UKismetMathLibrary", "math_vector", "Truncates each component to int", ["vector", "3d", "spatial", "position"])
_n("Vector_Distance", "UKismetMathLibrary", "math_vector", "3D distance between points", ["vector", "3d", "spatial", "position"])
_n("Vector_DistanceSquared", "UKismetMathLibrary", "math_vector", "Squared 3D distance (faster)", ["vector", "3d", "spatial", "position"])
_n("Vector_Distance2D", "UKismetMathLibrary", "math_vector", "2D distance (ignoring Z)", ["vector", "3d", "spatial", "position"])
_n("Vector_Distance2DSquared", "UKismetMathLibrary", "math_vector", "Squared 2D distance", ["vector", "3d", "spatial", "position"])
_n("VSize", "UKismetMathLibrary", "math_vector", "Vector magnitude", ["vector", "3d", "spatial", "position"])
_n("VSizeSquared", "UKismetMathLibrary", "math_vector", "Squared magnitude", ["vector", "3d", "spatial", "position"])
_n("VSizeXY", "UKismetMathLibrary", "math_vector", "XY plane magnitude", ["vector", "3d", "spatial", "position"])
_n("VSizeXYSquared", "UKismetMathLibrary", "math_vector", "Squared XY magnitude", ["vector", "3d", "spatial", "position"])
_n("Vector_IsNearlyZero", "UKismetMathLibrary", "math_vector", "Near-zero check with tolerance", ["vector", "3d", "spatial", "position"])
_n("Vector_IsZero", "UKismetMathLibrary", "math_vector", "Exact zero check", ["vector", "3d", "spatial", "position"])
_n("Vector_IsNAN", "UKismetMathLibrary", "math_vector", "Checks for NaN values", ["vector", "3d", "spatial", "position"])
_n("Vector_IsUniform", "UKismetMathLibrary", "math_vector", "All components nearly equal", ["vector", "3d", "spatial", "position"])
_n("Vector_IsUnit", "UKismetMathLibrary", "math_vector", "Is unit length", ["vector", "3d", "spatial", "position"])
_n("Vector_IsNormal", "UKismetMathLibrary", "math_vector", "Is normalized", ["vector", "3d", "spatial", "position"])
_n("Normal", "UKismetMathLibrary", "math_vector", "Returns normalized vector", ["vector", "3d", "spatial", "position"])
_n("Vector_Normal2D", "UKismetMathLibrary", "math_vector", "Returns 2D-normalized vector", ["vector", "3d", "spatial", "position"])
_n("Vector_NormalUnsafe", "UKismetMathLibrary", "math_vector", "Normalize without zero check", ["vector", "3d", "spatial", "position"])
_n("Vector_Normalize", "UKismetMathLibrary", "math_vector", "Normalizes in-place", ["vector", "3d", "spatial", "position"])
_n("Vector_Reciprocal", "UKismetMathLibrary", "math_vector", "Returns 1/component for each", ["vector", "3d", "spatial", "position"])
_n("GetReflectionVector", "UKismetMathLibrary", "math_vector", "Reflects direction off surface", ["vector", "3d", "spatial", "position"])
_n("MirrorVectorByNormal", "UKismetMathLibrary", "math_vector", "Mirrors vector by normal", ["vector", "3d", "spatial", "position"])
_n("Vector_MirrorByPlane", "UKismetMathLibrary", "math_vector", "Mirrors vector by plane", ["vector", "3d", "spatial", "position"])
_n("Vector_SnappedToGrid", "UKismetMathLibrary", "math_vector", "Snaps components to grid", ["vector", "3d", "spatial", "position"])
_n("ProjectVectorOnToVector", "UKismetMathLibrary", "math_vector", "Projects one vector onto another", ["vector", "3d", "spatial", "position"])
_n("ProjectPointOnToPlane", "UKismetMathLibrary", "math_vector", "Projects point onto plane", ["vector", "3d", "spatial", "position"])
_n("ProjectVectorOnToPlane", "UKismetMathLibrary", "math_vector", "Projects vector onto plane", ["vector", "3d", "spatial", "position"])
_n("FindLookAtRotation", "UKismetMathLibrary", "math_vector", "Rotation needed to look from start to target", ["vector", "3d", "spatial", "position"])
_n("FindClosestPointOnSegment", "UKismetMathLibrary", "math_vector", "Nearest point on line segment", ["vector", "3d", "spatial", "position"])
_n("FindClosestPointOnLine", "UKismetMathLibrary", "math_vector", "Nearest point on infinite line", ["vector", "3d", "spatial", "position"])
_n("FindNearestPointsOnLineSegments", "UKismetMathLibrary", "math_vector", "Closest points between two segments", ["vector", "3d", "spatial", "position"])
_n("GetPointDistanceToSegment", "UKismetMathLibrary", "math_vector", "Distance from point to segment", ["vector", "3d", "spatial", "position"])
_n("GetPointDistanceToLine", "UKismetMathLibrary", "math_vector", "Distance from point to infinite line", ["vector", "3d", "spatial", "position"])

# ===================================================================
# ROTATOR (31 nodes)
# Note: ClampAngle and RotatorFromAxisAndAngle also appear in other
# sections (Float, Vector). Last registration wins in BLUEPRINT_NODES
# dict -- these entries represent the rotator-context versions.
# ===================================================================
_n("MakeRotator", "UKismetMathLibrary", "math_rotator", "Creates rotator from Roll, Pitch, Yaw", ["rotation", "orientation", "spatial"])
_n("MakeRotFromX", "UKismetMathLibrary", "math_rotator", "Creates rotation aligning X with direction", ["rotation", "orientation", "spatial"])
_n("MakeRotFromY", "UKismetMathLibrary", "math_rotator", "Creates rotation aligning Y with direction", ["rotation", "orientation", "spatial"])
_n("MakeRotFromZ", "UKismetMathLibrary", "math_rotator", "Creates rotation aligning Z with direction", ["rotation", "orientation", "spatial"])
_n("MakeRotFromXY", "UKismetMathLibrary", "math_rotator", "Creates rotation from X and Y directions", ["rotation", "orientation", "spatial"])
_n("MakeRotFromXZ", "UKismetMathLibrary", "math_rotator", "Creates rotation from X and Z directions", ["rotation", "orientation", "spatial"])
_n("MakeRotFromYX", "UKismetMathLibrary", "math_rotator", "Creates rotation from Y and X directions", ["rotation", "orientation", "spatial"])
_n("MakeRotFromYZ", "UKismetMathLibrary", "math_rotator", "Creates rotation from Y and Z directions", ["rotation", "orientation", "spatial"])
_n("MakeRotFromZX", "UKismetMathLibrary", "math_rotator", "Creates rotation from Z and X directions", ["rotation", "orientation", "spatial"])
_n("MakeRotFromZY", "UKismetMathLibrary", "math_rotator", "Creates rotation from Z and Y directions", ["rotation", "orientation", "spatial"])
_n("BreakRotator", "UKismetMathLibrary", "math_rotator", "Breaks rotator into Roll, Pitch, Yaw", ["rotation", "orientation", "spatial"])
_n("BreakRotIntoAxes", "UKismetMathLibrary", "math_rotator", "Breaks rotator into forward/right/up axes", ["rotation", "orientation", "spatial"])
_n("ComposeRotators", "UKismetMathLibrary", "math_rotator", "Combines two rotations (A * B)", ["rotation", "orientation", "spatial"])
_n("NegateRotator", "UKismetMathLibrary", "math_rotator", "Returns negated rotator", ["rotation", "orientation", "spatial"])
_n("GetForwardVector", "UKismetMathLibrary", "math_rotator", "Forward direction from rotator", ["rotation", "orientation", "spatial"])
_n("GetRightVector", "UKismetMathLibrary", "math_rotator", "Right direction from rotator", ["rotation", "orientation", "spatial"])
_n("GetUpVector", "UKismetMathLibrary", "math_rotator", "Up direction from rotator", ["rotation", "orientation", "spatial"])
_n("Conv_RotatorToVector", "UKismetMathLibrary", "math_rotator", "Gets X direction after rotation", ["rotation", "orientation", "spatial"])
_n("Conv_RotatorToTransform", "UKismetMathLibrary", "math_rotator", "Rotator to transform conversion", ["rotation", "orientation", "spatial"])
_n("NormalizeAxis", "UKismetMathLibrary", "math_rotator", "Normalizes angle to [-180, 180]", ["rotation", "orientation", "spatial"])
_n("ClampAngle", "UKismetMathLibrary", "math_rotator", "Clamps angle to [Min, Max]", ["rotation", "orientation", "spatial"])
_n("RLerp", "UKismetMathLibrary", "math_rotator", "Rotator linear interpolation", ["rotation", "orientation", "spatial"])
_n("REase", "UKismetMathLibrary", "math_rotator", "Rotator eased interpolation", ["rotation", "orientation", "spatial"])
_n("RInterpTo", "UKismetMathLibrary", "math_rotator", "Rotator interpolation toward target", ["rotation", "orientation", "spatial"])
_n("RInterpTo_Constant", "UKismetMathLibrary", "math_rotator", "Constant-speed rotator interpolation", ["rotation", "orientation", "spatial"])
_n("RotatorFromAxisAndAngle", "UKismetMathLibrary", "math_rotator", "Creates rotator from axis + angle", ["rotation", "orientation", "spatial"])
_n("InvertRotator", "UKismetMathLibrary", "math_rotator", "Inverts the rotator (reverse rotation)", ["rotation", "orientation", "spatial"])
_n("SelectRotator", "UKismetMathLibrary", "math_rotator", "Selects A or B based on boolean", ["rotation", "orientation", "spatial"])
_n("Delta_Rotator", "UKismetMathLibrary", "math_rotator", "Shortest path delta between two rotators", ["rotation", "orientation", "spatial"])
_n("EqualEqual_RotatorRotator", "UKismetMathLibrary", "math_rotator", "Approximate equality", ["rotation", "orientation", "spatial"])
_n("NotEqual_RotatorRotator", "UKismetMathLibrary", "math_rotator", "Approximate inequality", ["rotation", "orientation", "spatial"])

# ===================================================================
# QUATERNION (21 nodes)
# ===================================================================
_n("MakeQuat", "UKismetMathLibrary", "math_quat", "Creates quaternion from X, Y, Z, W", ["quaternion", "rotation", "3d"])
_n("Quat_MakeFromEuler", "UKismetMathLibrary", "math_quat", "Quaternion from Euler angles", ["quaternion", "rotation", "3d"])
_n("BreakQuat", "UKismetMathLibrary", "math_quat", "Breaks quaternion into components", ["quaternion", "rotation", "3d"])
_n("Quat_IsIdentity", "UKismetMathLibrary", "math_quat", "Checks if identity quaternion", ["quaternion", "rotation", "3d"])
_n("Quat_IsNonFinite", "UKismetMathLibrary", "math_quat", "Checks for NaN/Inf values", ["quaternion", "rotation", "3d"])
_n("Quat_Exp", "UKismetMathLibrary", "math_quat", "Quaternion exponential", ["quaternion", "rotation", "3d"])
_n("Quat_Log", "UKismetMathLibrary", "math_quat", "Quaternion logarithm", ["quaternion", "rotation", "3d"])
_n("Quat_Inversed", "UKismetMathLibrary", "math_quat", "Returns inverse quaternion", ["quaternion", "rotation", "3d"])
_n("Quat_Normalized", "UKismetMathLibrary", "math_quat", "Returns normalized quaternion", ["quaternion", "rotation", "3d"])
_n("Quat_RotateVector", "UKismetMathLibrary", "math_quat", "Rotates vector by quaternion", ["quaternion", "rotation", "3d"])
_n("Quat_UnrotateVector", "UKismetMathLibrary", "math_quat", "Inverse-rotates vector", ["quaternion", "rotation", "3d"])
_n("Quat_VectorForward", "UKismetMathLibrary", "math_quat", "Forward direction from quat", ["quaternion", "rotation", "3d"])
_n("Quat_VectorRight", "UKismetMathLibrary", "math_quat", "Right direction from quat", ["quaternion", "rotation", "3d"])
_n("Quat_VectorUp", "UKismetMathLibrary", "math_quat", "Up direction from quat", ["quaternion", "rotation", "3d"])
_n("Quat_Rotator", "UKismetMathLibrary", "math_quat", "Converts quaternion to rotator", ["quaternion", "rotation", "3d"])
_n("Quat_Euler", "UKismetMathLibrary", "math_quat", "Converts quaternion to Euler angles", ["quaternion", "rotation", "3d"])
_n("Quat_SetFromEuler", "UKismetMathLibrary", "math_quat", "Sets quaternion from Euler angles", ["quaternion", "rotation", "3d"])
_n("Quat_SetComponents", "UKismetMathLibrary", "math_quat", "Sets XYZW components", ["quaternion", "rotation", "3d"])
_n("Quat_AngularDistance", "UKismetMathLibrary", "math_quat", "Angular distance between two quats", ["quaternion", "rotation", "3d"])
_n("Quat_EnforceShortestArcWith", "UKismetMathLibrary", "math_quat", "Ensures shortest arc interpolation", ["quaternion", "rotation", "3d"])
_n("Quat_Slerp", "UKismetMathLibrary", "math_quat", "Spherical interpolation between quats", ["quaternion", "rotation", "3d"])

# ===================================================================
# TRANSFORM (19 nodes)
# Note: Conv_VectorToTransform and Conv_RotatorToTransform also appear
# in Vector and Rotator sections. Last registration wins -- these
# entries re-register under math_transform category for transform context.
# ===================================================================
_n("MakeTransform", "UKismetMathLibrary", "math_transform", "Creates from location, rotation, scale", ["transform", "position", "scale"])
_n("BreakTransform", "UKismetMathLibrary", "math_transform", "Breaks into location, rotation, scale", ["transform", "position", "scale"])
_n("ComposeTransforms", "UKismetMathLibrary", "math_transform", "Composes A * B", ["transform", "position", "scale"])
_n("InvertTransform", "UKismetMathLibrary", "math_transform", "Returns inverted transform", ["transform", "position", "scale"])
_n("ConvertTransformToRelative", "UKismetMathLibrary", "math_transform", "Converts to relative space", ["transform", "position", "scale"])
_n("TransformLocation", "UKismetMathLibrary", "math_transform", "Transforms a position", ["transform", "position", "scale"])
_n("TransformDirection", "UKismetMathLibrary", "math_transform", "Transforms a direction (ignores translation)", ["transform", "position", "scale"])
_n("InverseTransformLocation", "UKismetMathLibrary", "math_transform", "Inverse-transforms a position", ["transform", "position", "scale"])
_n("InverseTransformDirection", "UKismetMathLibrary", "math_transform", "Inverse-transforms a direction", ["transform", "position", "scale"])
_n("InverseTransformRotation", "UKismetMathLibrary", "math_transform", "Inverse-transforms a rotation", ["transform", "position", "scale"])
_n("TLerp", "UKismetMathLibrary", "math_transform", "Transform linear interpolation", ["transform", "position", "scale"])
_n("TEase", "UKismetMathLibrary", "math_transform", "Transform eased interpolation", ["transform", "position", "scale"])
_n("TInterpTo", "UKismetMathLibrary", "math_transform", "Transform interpolation toward target", ["transform", "position", "scale"])
_n("SelectTransform", "UKismetMathLibrary", "math_transform", "Selects A or B based on boolean", ["transform", "position", "scale"])
_n("EqualEqual_TransformTransform", "UKismetMathLibrary", "math_transform", "Transform equality check", ["transform", "position", "scale"])
_n("Transform_Identity", "UKismetMathLibrary", "math_transform", "Returns identity transform", ["transform", "position", "scale"])
_n("Conv_VectorToTransform", "UKismetMathLibrary", "math_transform", "Vector to transform (as location)", ["transform", "position", "scale"])
_n("Conv_RotatorToTransform", "UKismetMathLibrary", "math_transform", "Rotator to transform", ["transform", "position", "scale"])
_n("Conv_MatrixToTransform", "UKismetMathLibrary", "math_transform", "Matrix to transform", ["transform", "position", "scale"])
